// apps/react-app/src/App.tsx
import { HashRouter, Routes, Route, NavLink } from 'react-router-dom';
import Home from './pages/Home';
import About from './pages/About';
import './App.css';

export default function App() {
  return (
    <HashRouter>
      <header>
        <h1>GeneralStore <span className="tech-badge">React</span></h1>
        <nav>
          <NavLink to="/" className="nav-link" end>Home</NavLink>
          <NavLink to="/about" className="nav-link">About</NavLink>
        </nav>
      </header>

      <main>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/about" element={<About />} />
        </Routes>
      </main>

      <footer>
        <p>&copy; 2026 GeneralStore — React Test Target</p>
      </footer>
    </HashRouter>
  );
}

// apps/vue-app/src/App.vue
<template>
  <v-app>
    <header>
      <h1>GeneralStore <span class="tech-badge">Vue</span></h1>
      <nav>
        <RouterLink to="/" class="nav-link" active-class="active" :exact="true">Home</RouterLink>
        <RouterLink to="/about" class="nav-link" active-class="active">About</RouterLink>
      </nav>
    </header>

    <main>
      <RouterView />
    </main>

    <footer>
      <p>&copy; 2026 GeneralStore — Vue Test Target</p>
    </footer>
  </v-app>
</template>

<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
</script>
