// apps/vue-app/src/App.vue
<template>
  <v-app>
    <header>
      <h1>GeneralStore <span class="tech-badge">Vue</span></h1>
      <nav>
        <RouterLink to="/" class="nav-link" active-class="active" :exact="true">Home</RouterLink>
        <RouterLink to="/about" class="nav-link" active-class="active">About</RouterLink>
      </nav>
    </header>

    <main>
      <RouterView />
    </main>

    <footer>
      <p>&copy; 2026 GeneralStore — Vue Test Target</p>
    </footer>
  </v-app>
</template>

<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router';
</script>

// apps/angular-app/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <header>
      <h1>GeneralStore <span class="tech-badge">Angular</span></h1>
      <nav>
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }"
           class="nav-link">Home</a>
        <a routerLink="/about" routerLinkActive="active"
           class="nav-link">About</a>
      </nav>
    </header>

    <main>
      <router-outlet />
    </main>

    <footer>
      <p>&copy; 2026 GeneralStore — Angular Test Target</p>
    </footer>
  `,
  styles: [],
})
export class AppComponent {}
