// apps/angular-app/src/app/pages/home.component.ts
import { Component, OnInit, OnDestroy, inject, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { MatDialog, MatDialogModule } from '@angular/material/dialog';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { PRODUCTS, CATEGORIES, SHIPPING, type Product } from '../data';
import { ProductDialogComponent } from './product-dialog.component';

type SortKey = 'name' | 'price' | 'category' | 'stock' | null;

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatDialogModule,
    MatSnackBarModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatInputModule,
  ],
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css'],
  encapsulation: ViewEncapsulation.None,
})
export class HomeComponent implements OnInit, OnDestroy {
  private dialog = inject(MatDialog);
  private snackBar = inject(MatSnackBar);

  // Data
  readonly categories = CATEGORIES;
  readonly shippingOptions = Object.entries(SHIPPING);

  // Filter state
  searchTerm = '';
  selectedCategory = 'All';
  inStockOnly = false;

  // Sort state
  sortKey: SortKey = null;
  sortAsc = true;

  // Interactive state
  quantity = 1;
  selectedShipping = 'standard';
  deliveryDate: Date | null = null;
  actionOutput = '';
  validationMsg = '';
  showValidation = false;

  // Toast
  toastMsg = '';
  showToast = false;
  private toastTimeout: ReturnType<typeof setTimeout> | null = null;

  // Delayed content
  delayedText = 'Loading recommendations…';
  private delayedTimeout: ReturnType<typeof setTimeout> | null = null;

  ngOnInit(): void {
    this.delayedTimeout = setTimeout(() => {
      this.delayedText = 'You might also like: USB-C Hub, Winter Jacket, Cooking Basics';
    }, 1500);
  }

  ngOnDestroy(): void {
    if (this.delayedTimeout) clearTimeout(this.delayedTimeout);
    if (this.toastTimeout) clearTimeout(this.toastTimeout);
  }

  // ===== Computed =====
  get filteredProducts(): Product[] {
    let filtered = PRODUCTS.filter((p) => {
      if (this.searchTerm && !p.name.toLowerCase().includes(this.searchTerm.toLowerCase())) return false;
      if (this.selectedCategory !== 'All' && p.category !== this.selectedCategory) return false;
      if (this.inStockOnly && !p.inStock) return false;
      return true;
    });

    if (this.sortKey) {
      filtered = [...filtered].sort((a, b) => {
        let valA: string | number;
        let valB: string | number;

        switch (this.sortKey) {
          case 'name':     valA = a.name.toLowerCase(); valB = b.name.toLowerCase(); break;
          case 'price':    valA = a.price; valB = b.price; break;
          case 'category': valA = a.category.toLowerCase(); valB = b.category.toLowerCase(); break;
          case 'stock':    valA = a.inStock ? 1 : 0; valB = b.inStock ? 1 : 0; break;
          default:         valA = 0; valB = 0;
        }

        if (valA < valB) return this.sortAsc ? -1 : 1;
        if (valA > valB) return this.sortAsc ? 1 : -1;
        return 0;
      });
    }

    return filtered;
  }

  get shippingCost(): string {
    return `$${SHIPPING[this.selectedShipping].cost.toFixed(2)}`;
  }

  get formattedDate(): string {
    if (!this.deliveryDate) return '';
    return this.deliveryDate.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  }

  // ===== Handlers =====
  handleSort(key: SortKey): void {
    if (this.sortKey === key) {
      this.sortAsc = !this.sortAsc;
    } else {
      this.sortKey = key;
      this.sortAsc = true;
    }
  }

  getSortIndicator(key: string): string {
    if (this.sortKey !== key) return ' ⇅';
    return this.sortAsc ? ' ▲' : ' ▼';
  }

  increment(): void {
    if (this.quantity < 99) this.quantity++;
  }

  decrement(): void {
    if (this.quantity > 1) this.quantity--;
  }

  addToCart(product: Product): void {
    const msg = `Added ${this.quantity}x ${product.name} to cart`;
    this.actionOutput = msg;
    this.showToastMessage(msg);
  }

  handleActionButton(): void {
    const products = this.filteredProducts;
    if (products.length === 0) {
      this.validationMsg = 'Please enter a search term';
      this.showValidation = true;
      return;
    }
    this.showValidation = false;
    this.addToCart(products[0]);
  }

  handleSearchKeyDown(event: KeyboardEvent): void {
    if (event.key === 'Enter') {
      if (!this.searchTerm.trim()) {
        this.validationMsg = 'Please enter a search term';
        this.showValidation = true;
      } else {
        this.showValidation = false;
      }
    }
  }

  openModal(product: Product): void {
    const dialogRef = this.dialog.open(ProductDialogComponent, {
      data: product,
      width: '450px',
      panelClass: 'product-dialog-panel',
    });
  }

  private showToastMessage(msg: string): void {
    // Use MatSnackBar for technology-native toast
    const snackBarRef = this.snackBar.open(msg, undefined, {
      duration: 3000,
      horizontalPosition: 'end',
      verticalPosition: 'bottom',
      panelClass: ['generalstore-snackbar'],
    });

    // Also show inline toast for UI contract
    this.toastMsg = msg;
    this.showToast = true;
    if (this.toastTimeout) clearTimeout(this.toastTimeout);
    this.toastTimeout = setTimeout(() => {
      this.showToast = false;
    }, 3000);
  }
}

<!-- Filter Controls -->
<div class="filter-bar">
  <div class="filter-group">
    <label for="search-input">Search Products</label>
    <input
      type="text"
      id="search-input"
     
      placeholder="Search by name…"
      [(ngModel)]="searchTerm"
      (keydown)="handleSearchKeyDown($event)"
    />
  </div>

  <div class="filter-group">
    <label for="category-select">Category</label>
    <select id="category-select" [(ngModel)]="selectedCategory">
      @for (cat of categories; track cat) {
        <option [value]="cat">{{ cat }}</option>
      }
    </select>
  </div>

  <div class="filter-group filter-checkbox">
    <input
      type="checkbox"
      id="stock-checkbox"
     
      [(ngModel)]="inStockOnly"
    />
    <label for="stock-checkbox">Show only in-stock items</label>
  </div>
</div>

<!-- Validation Message -->
@if (showValidation) {
  <div class="validation-message" aria-live="polite">
    {{ validationMsg }}
  </div>
}

<!-- Product Data Table -->
<table class="data-table">
  <thead>
    <tr>
      <th role="button" tabindex="0"
          data-sort-key="name"
          aria-label="Sort by Name"
          (click)="handleSort('name')"
          (keydown.enter)="handleSort('name')"
          (keydown.space)="$event.preventDefault(); handleSort('name')">
        Name{{ getSortIndicator('name') }}
      </th>
      <th role="button" tabindex="0"
          data-sort-key="price"
          aria-label="Sort by Price"
          (click)="handleSort('price')"
          (keydown.enter)="handleSort('price')"
          (keydown.space)="$event.preventDefault(); handleSort('price')">
        Price{{ getSortIndicator('price') }}
      </th>
      <th role="button" tabindex="0"
          data-sort-key="category"
          aria-label="Sort by Category"
          (click)="handleSort('category')"
          (keydown.enter)="handleSort('category')"
          (keydown.space)="$event.preventDefault(); handleSort('category')">
        Category{{ getSortIndicator('category') }}
      </th>
      <th role="button" tabindex="0"
          data-sort-key="stock"
          aria-label="Sort by Stock"
          (click)="handleSort('stock')"
          (keydown.enter)="handleSort('stock')"
          (keydown.space)="$event.preventDefault(); handleSort('stock')">
        Stock{{ getSortIndicator('stock') }}
      </th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    @if (filteredProducts.length === 0) {
      <tr class="empty-state">
        <td colspan="5">No products found.</td>
      </tr>
    } @else {
      @for (product of filteredProducts; track product.name) {
        <tr>
          <td>
            <button class="view-details-btn"
                    (click)="openModal(product)">
              {{ product.name }}
            </button>
          </td>
          <td>${{ product.price.toFixed(2) }}</td>
          <td>{{ product.category }}</td>
          <td>{{ product.inStock ? 'Yes' : 'No' }}</td>
          <td>
            <button class="btn-primary btn-sm"
                    (click)="addToCart(product)">
              Add to Cart
            </button>
          </td>
        </tr>
      }
    }
  </tbody>
</table>

<!-- Order Controls -->
<div class="order-controls">
  <!-- Quantity Stepper -->
  <fieldset class="control-group">
    <legend>Quantity</legend>
    <div class="stepper">
      <button aria-label="Decrease quantity"
              [disabled]="quantity <= 1" (click)="decrement()">−</button>
      <input type="number" id="quantity-input"
             [value]="quantity" min="1" max="99" readonly aria-label="Quantity" />
      <button aria-label="Increase quantity"
              [disabled]="quantity >= 99" (click)="increment()">+</button>
    </div>
  </fieldset>

  <!-- Shipping Radio Group -->
  <fieldset class="control-group radio-group">
    <legend>Shipping Method</legend>
    @for (option of shippingOptions; track option[0]) {
      <label>
        <input type="radio" name="shipping" [value]="option[0]"
               [(ngModel)]="selectedShipping" />
        {{ option[1].label }} — <span>${{ option[1].cost.toFixed(2) }}</span>
      </label>
    }
    <div class="radio-output" aria-live="polite">
      Shipping: {{ shippingCost }}
    </div>
  </fieldset>

  <!-- Date Picker (Angular Material) -->
  <fieldset class="control-group">
    <legend>Delivery Date</legend>
    <mat-form-field appearance="outline">
      <mat-label>Choose a date</mat-label>
      <input matInput [matDatepicker]="picker" [(ngModel)]="deliveryDate" />
      <mat-datepicker-toggle matIconSuffix [for]="picker"></mat-datepicker-toggle>
      <mat-datepicker #picker></mat-datepicker>
    </mat-form-field>
    <div class="date-output" aria-live="polite">
      {{ formattedDate }}
    </div>
  </fieldset>
</div>

<!-- Action Button + Output -->
<div class="action-area">
  <button class="btn-primary" (click)="handleActionButton()">
    Add to Cart
  </button>
  <div class="action-output" aria-live="polite">
    {{ actionOutput }}
  </div>
</div>

<!-- Item List -->
<div class="section">
  <h2>Popular Items</h2>
  <ul class="item-list">
    <li>Wireless Mouse</li>
    <li>Bluetooth Keyboard</li>
    <li>Running Shoes</li>
  </ul>
</div>

<!-- Delayed Content -->
<div class="section">
  <h2>Recommendations</h2>
  <div aria-live="polite">{{ delayedText }}</div>
</div>

<!-- Toast (inline for UI contract) -->
@if (showToast) {
  <div class="toast" role="status" aria-live="polite">
    {{ toastMsg }}
  </div>
}

// apps/react-app/src/pages/Home.tsx
import { useState, useEffect, useCallback } from 'react';
import DatePicker from 'react-datepicker';
import 'react-datepicker/dist/react-datepicker.css';
import { PRODUCTS, CATEGORIES, SHIPPING, type Product } from '../data';

type SortKey = 'name' | 'price' | 'category' | 'stock' | null;

export default function Home() {
  // ===== Filter state =====
  const [searchTerm, setSearchTerm] = useState('');
  const [category, setCategory] = useState('All');
  const [inStockOnly, setInStockOnly] = useState(false);

  // ===== Sort state =====
  const [sortKey, setSortKey] = useState<SortKey>(null);
  const [sortAsc, setSortAsc] = useState(true);

  // ===== Interactive state =====
  const [quantity, setQuantity] = useState(1);
  const [shipping, setShipping] = useState('standard');
  const [deliveryDate, setDeliveryDate] = useState<Date | null>(null);
  const [actionOutput, setActionOutput] = useState('');
  const [validationMsg, setValidationMsg] = useState('');
  const [showValidation, setShowValidation] = useState(false);

  // ===== Toast =====
  const [toastMsg, setToastMsg] = useState('');
  const [showToast, setShowToast] = useState(false);

  // ===== Modal =====
  const [modalProduct, setModalProduct] = useState<Product | null>(null);

  // ===== Delayed content =====
  const [delayedText, setDelayedText] = useState('Loading recommendations…');

  useEffect(() => {
    const timer = setTimeout(() => {
      setDelayedText('You might also like: USB-C Hub, Winter Jacket, Cooking Basics');
    }, 1500);
    return () => clearTimeout(timer);
  }, []);

  // ===== Toast auto-dismiss =====
  useEffect(() => {
    if (!showToast) return;
    const timer = setTimeout(() => setShowToast(false), 3000);
    return () => clearTimeout(timer);
  }, [showToast]);

  // ===== Filtering + Sorting =====
  const getFilteredProducts = useCallback(() => {
    let filtered = PRODUCTS.filter((p) => {
      if (searchTerm && !p.name.toLowerCase().includes(searchTerm.toLowerCase())) return false;
      if (category !== 'All' && p.category !== category) return false;
      if (inStockOnly && !p.inStock) return false;
      return true;
    });

    if (sortKey) {
      filtered = [...filtered].sort((a, b) => {
        let valA: string | number | boolean;
        let valB: string | number | boolean;

        switch (sortKey) {
          case 'name':     valA = a.name.toLowerCase(); valB = b.name.toLowerCase(); break;
          case 'price':    valA = a.price; valB = b.price; break;
          case 'category': valA = a.category.toLowerCase(); valB = b.category.toLowerCase(); break;
          case 'stock':    valA = a.inStock ? 1 : 0; valB = b.inStock ? 1 : 0; break;
        }

        if (valA < valB) return sortAsc ? -1 : 1;
        if (valA > valB) return sortAsc ? 1 : -1;
        return 0;
      });
    }

    return filtered;
  }, [searchTerm, category, inStockOnly, sortKey, sortAsc]);

  const filteredProducts = getFilteredProducts();

  // ===== Handlers =====
  function handleSort(key: SortKey) {
    if (sortKey === key) {
      setSortAsc(!sortAsc);
    } else {
      setSortKey(key);
      setSortAsc(true);
    }
  }

  function getSortIndicator(key: string) {
    if (sortKey !== key) return ' ⇅';
    return sortAsc ? ' ▲' : ' ▼';
  }

  function showToastMessage(msg: string) {
    setToastMsg(msg);
    setShowToast(true);
  }

  function addToCart(product: Product) {
    const msg = `Added ${quantity}x ${product.name} to cart`;
    setActionOutput(msg);
    showToastMessage(msg);
  }

  function handleActionButton() {
    if (filteredProducts.length === 0) {
      setValidationMsg('Please enter a search term');
      setShowValidation(true);
      return;
    }
    setShowValidation(false);
    addToCart(filteredProducts[0]);
  }

  function handleSearchKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter') {
      if (!searchTerm.trim()) {
        setValidationMsg('Please enter a search term');
        setShowValidation(true);
      } else {
        setShowValidation(false);
      }
    }
  }

  function formatDate(date: Date | null): string {
    if (!date) return '';
    return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  }

  function openModal(product: Product) {
    setModalProduct(product);
  }

  function closeModal() {
    setModalProduct(null);
  }

  return (
    <>
      {/* Filter Controls */}
      <div data-testid="table-filter" className="filter-bar">
        <div className="filter-group">
          <label htmlFor="search-input">Search Products</label>
          <input
            type="text"
            id="search-input"
            data-testid="text-input"
            placeholder="Search by name…"
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            onKeyDown={handleSearchKeyDown}
          />
        </div>
        <div className="filter-group">
          <label htmlFor="category-select">Category</label>
          <select
            id="category-select"
            data-testid="select-dropdown"
            value={category}
            onChange={(e) => setCategory(e.target.value)}
          >
            {CATEGORIES.map((c) => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
        </div>
        <div className="filter-group filter-checkbox">
          <input
            type="checkbox"
            id="stock-checkbox"
            data-testid="toggle-checkbox"
            checked={inStockOnly}
            onChange={(e) => setInStockOnly(e.target.checked)}
          />
          <label htmlFor="stock-checkbox">Show only in-stock items</label>
        </div>
      </div>

      {/* Validation Message */}
      {showValidation && (
        <div data-testid="validation-message" className="validation-message" aria-live="polite">
          {validationMsg}
        </div>
      )}

      {/* Product Data Table */}
      <table data-testid="data-table" className="data-table">
        <thead>
          <tr>
            <th data-testid="table-sort" role="button" tabIndex={0} aria-label="Sort by Name"
                onClick={() => handleSort('name')} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); handleSort('name'); }}}>
              Name{getSortIndicator('name')}
            </th>
            <th data-testid="table-sort" role="button" tabIndex={0} aria-label="Sort by Price"
                onClick={() => handleSort('price')} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); handleSort('price'); }}}>
              Price{getSortIndicator('price')}
            </th>
            <th data-testid="table-sort" role="button" tabIndex={0} aria-label="Sort by Category"
                onClick={() => handleSort('category')} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); handleSort('category'); }}}>
              Category{getSortIndicator('category')}
            </th>
            <th data-testid="table-sort" role="button" tabIndex={0} aria-label="Sort by Stock"
                onClick={() => handleSort('stock')} onKeyDown={(e) => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); handleSort('stock'); }}}>
              Stock{getSortIndicator('stock')}
            </th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {filteredProducts.length === 0 ? (
            <tr className="empty-row">
              <td colSpan={5} data-testid="empty-state">No products found.</td>
            </tr>
          ) : (
            filteredProducts.map((product) => (
              <tr key={product.name}>
                <td>
                  <button className="view-details-btn" data-testid="modal-trigger"
                          onClick={() => openModal(product)}>
                    {product.name}
                  </button>
                </td>
                <td>${product.price.toFixed(2)}</td>
                <td>{product.category}</td>
                <td>{product.inStock ? 'Yes' : 'No'}</td>
                <td>
                  <button className="btn-primary btn-sm" data-testid="action-button"
                          onClick={() => addToCart(product)}>
                    Add to Cart
                  </button>
                </td>
              </tr>
            ))
          )}
        </tbody>
      </table>

      {/* Order Controls */}
      <div className="order-controls">
        {/* Quantity Stepper */}
        <fieldset className="control-group">
          <legend>Quantity</legend>
          <div className="stepper">
            <button data-testid="quantity-decrement" aria-label="Decrease quantity"
                    disabled={quantity <= 1} onClick={() => setQuantity((q) => Math.max(1, q - 1))}>−</button>
            <input type="number" data-testid="quantity-input" id="quantity-input"
                   value={quantity} min={1} max={99} readOnly aria-label="Quantity" />
            <button data-testid="quantity-increment" aria-label="Increase quantity"
                    disabled={quantity >= 99} onClick={() => setQuantity((q) => Math.min(99, q + 1))}>+</button>
          </div>
        </fieldset>

        {/* Shipping Radio Group */}
        <fieldset className="control-group" data-testid="radio-group">
          <legend>Shipping Method</legend>
          {Object.entries(SHIPPING).map(([key, { label, cost }]) => (
            <label key={key}>
              <input type="radio" name="shipping" value={key}
                     checked={shipping === key} onChange={() => setShipping(key)} />
              {' '}{label} — <span>${cost.toFixed(2)}</span>
            </label>
          ))}
          <div data-testid="radio-output" className="radio-output" aria-live="polite">
            Shipping: ${SHIPPING[shipping].cost.toFixed(2)}
          </div>
        </fieldset>

        {/* Date Picker */}
        <fieldset className="control-group">
          <legend>Delivery Date</legend>
          <label htmlFor="delivery-date">Choose a date</label>
          <div data-testid="date-picker">
            <DatePicker
              id="delivery-date"
              selected={deliveryDate}
              onChange={(date: Date | null) => setDeliveryDate(date)}
              placeholderText="Select a date"
              dateFormat="MM/dd/yyyy"
              className="datepicker-input"
            />
          </div>
          <div data-testid="date-output" className="date-output" aria-live="polite">
            {formatDate(deliveryDate)}
          </div>
        </fieldset>
      </div>

      {/* Action Button + Output */}
      <div className="action-area">
        <button data-testid="action-button" className="btn-primary" onClick={handleActionButton}>
          Add to Cart
        </button>
        <div data-testid="action-output" className="action-output" aria-live="polite">
          {actionOutput}
        </div>
      </div>

      {/* Item List */}
      <div className="section">
        <h2>Popular Items</h2>
        <ul data-testid="item-list">
          <li>Wireless Mouse</li>
          <li>Bluetooth Keyboard</li>
          <li>Running Shoes</li>
        </ul>
      </div>

      {/* Delayed Content */}
      <div className="section">
        <h2>Recommendations</h2>
        <div data-testid="delayed-content" aria-live="polite">{delayedText}</div>
      </div>

      {/* Modal */}
      {modalProduct && (
        <dialog data-testid="modal-dialog" className="modal" open
                onClick={(e) => { if (e.target === e.currentTarget) closeModal(); }}>
          <div className="modal-content">
            <h2>{modalProduct.name}</h2>
            <p>
              {modalProduct.name} — ${modalProduct.price.toFixed(2)} | Category: {modalProduct.category} | {modalProduct.inStock ? 'In Stock' : 'Out of Stock'}
            </p>
            <button data-testid="modal-close" className="btn-secondary" aria-label="Close dialog"
                    onClick={closeModal}>
              Close
            </button>
          </div>
        </dialog>
      )}

      {/* Toast */}
      {showToast && (
        <div data-testid="toast-notification" className="toast" role="status" aria-live="polite">
          {toastMsg}
        </div>
      )}
    </>
  );
}
