// apps/nextjs-app/app/about/page.tsx
export default function About() {
  return (
    <p className="about-text">
      Welcome to <strong>GeneralStore</strong> — your one-stop shop for everyday essentials.
      We carry electronics, clothing, and books at unbeatable prices. This store is a demo
      application built with Next.js and TypeScript, featuring server-side rendering.
    </p>
  );
}

// apps/vue-app/src/pages/About.vue
<template>
  <p class="about-text">
    Welcome to <strong>GeneralStore</strong> — your one-stop shop for everyday essentials.
    We carry electronics, clothing, and books at unbeatable prices. This store is a demo
    application built with Vue 3 and TypeScript, powered by Vite.
  </p>
</template>
